### PR TITLE
Add possibility to store a 'referencedBy' tracker

### LINKED ISSUE #255: Store referencedByTracker
In the Maven Help Plugin, we [want to enrich](https://issues.apache.org/jira/browse/MPH-183) our "verbose effective POM" by not only saying _where_ a particular dependency is declared but also _why_ that location is actually in scope. This should aid users who want to upgrade a particular library imported through a chain of "bill of materials".

For this to work, we need a place in the Modello-generated classes to keep track of "why we loaded this model". From a Maven perspective, we might call this the "referencing model" with type`InputLocation`. To actually be able to store this information, the Modello-generated classes need something similar to the `locationTracker` and the `sourceTracker` - let's call it the `referencedByTracker` for now.

When building its dependency management model, Maven will then populate this field and finally, the Maven Help Plugin can display this to the end user.

I'm mainly writing this issue so the pull request can refer to it. We could discuss the idea here, and the actual implementation (which I will soon publish) in the pull request.

### PR DESCRIPTION
**Pull request by mthmulders**
Closes #255 

I'm relatively new to the Modello codebase. I did my best to maintain the existing code style, but please let me know if I missed something. The approach follows the `sourceTracker` and `locationTracker` fields, I hope that's a correct way to implement #255.

### CODE REVIEW

**Comment by mthmulders** [comment]
I guess we need to bump the minor version number for this, as we're introducing a new feature. That's why I've added **src/site/resources/xsd/modello-2.1.0.xsd** (rather than updating **src/site/resources/xsd/modello-2.0.0.xsd**). I've not included the version bump in all the **pom.xml** files, but I can push that if you consider it part of the PR.

**Comment by gnodet** [comment]
Fwiw, maven 4.x does not use the modello java/reader generators, so if you want to include that in maven, you should have a look at the Velocity template which is now used to generate the model and the reader:
  https://github.com/apache/maven/blob/master/api/maven-api-model/src/main/mdo/model.vm
  https://github.com/apache/maven/blob/master/maven-model/src/main/mdo/model-v3.vm
  https://github.com/apache/maven/blob/master/maven-model/src/main/mdo/reader-ex.vm

**Comment by mthmulders** [comment]
Thanks for pointing that out. Strange thing is, these changes did provide the correct changes in Modello-generated code. But I'll rework to use the Velocity engine anyway!

**Comment by hboutemy** [comment]
@mthmulders if you provided a new Modello xsd, I suppose `modello.mdo` should have been modified, isn't it?
https://github.com/codehaus-plexus/modello/blob/master/src/main/mdo/modello.mdo

**Comment by mthmulders** [comment]
@hboutemy, given the Velocity templates are maintained at apache/maven, I think we don't need changes in Modello anymore. I haven't found enough time yet to rewrite all of the necessary bits for [MPH-183](https://issues.apache.org/jira/browse/MPH-183), so I'm not yet 100% sure.

**Comment by hboutemy** [comment]
> given the Velocity templates are maintained at apache/maven

ok, if you only target Maven 4

> I'm not yet 100% sure

ok, I'll do the 2.1.0 release without this PR, we'll see later, thanks for your quick feedback

**Comment by mthmulders** [comment]
> ok, if you only target Maven 4

Confirmed. I don't think I want to do the additional effort of building this in Maven 3.x.

**Comment by mthmulders** [comment]
@slachiewicz I think so, but I need to refresh on the subject. I hope to be back later this week with an update.

**Pull request closed without merging**
