### PR TITLE
Fix ModelloCli broken after moving from Plexus to JSR330

### PR DESCRIPTION
**Pull request by fridrich**
This is my attempt at least to make the ModelloCli.java at least start and run. It still throws an exception on simple models. But at least the guice bindings look correct and the thing is at least starting and running.

### CODE REVIEW

**Comment by fridrich** [comment]
[model.mdo.gz](https://github.com/codehaus-plexus/modello/files/14960930/model.mdo.gz)
This is the model I am using and the command-line options are "model.mdo java . 1.0.0 false 8 UTF-8"
This gives me this message:
org.codehaus.modello.ModelloRuntimeException: Duplicate field in null: null.
	at org.codehaus.modello.model.ModelClass.addField(ModelClass.java:153)
	at org.codehaus.modello.core.io.ModelReader.parseFields(ModelReader.java:317)
	at org.codehaus.modello.core.io.ModelReader.parseClasses(ModelReader.java:215)
	at org.codehaus.modello.core.io.ModelReader.parseModel(ModelReader.java:120)
	at org.codehaus.modello.core.io.ModelReader.loadModel(ModelReader.java:95)
	at org.codehaus.modello.core.DefaultModelloCore.loadModel(DefaultModelloCore.java:106)
	at org.codehaus.modello.Modello.generate(Modello.java:46)
	at org.codehaus.modello.ModelloCli.main(ModelloCli.java:145)

**Comment by fridrich** [comment]
#434

**Comment by fridrich** [comment]
This version is now working for me and from my side, it is ready to get integrated. I don't know which kind of test to write for a command-line tool so that it does not regress any more. Please, advise.
Btw, the guice path I tried before is largely convoluted, and complicated. After I studied the commit 3c05d7a67847c00723ec363243c213fa32b017ee, I understood the problem.

**Comment by fridrich** [comment]
The latest version actually restores the possibility to instantiate directly the Modello class, since I see now that some Fedora tools in javapackages-bootstrap do it. So that partially reverts one commit for the two files and adds the configuration. Like that, stuff out there that was using new Modello() will be able to use it still. Including that it throws the same exception as in 2.1.2

**Comment by fridrich** [comment]
It would be good to have some test for this. Minimum that it can generate simple java files from a model. But for that, one needs basically the whole classpath including the plugins.

**Comment by fridrich** [comment]
This is running in openSUSE since and generates on command-line the correct Java files. Any chance to have it reviewed?

**Comment by fridrich** [comment]
Where is this standing?

**Comment by fridrich** [comment]
ping?

**Comment by cstamas** [comment]
@fridrich do you have any needed change in here, or goal was really just to make it work (again)? As if latter, I'd like to have this PR superseded by https://github.com/codehaus-plexus/modello/pull/452 as it does more correct approach IMO (using shade plugin that is able to process Sisu index and Plexus XMLs).

**Comment by fridrich** [comment]
I would really love to have at least this in https://github.com/codehaus-plexus/modello/commit/90352d3cd8de0382be73d5ce16b5f9d96469e39c
The reasons are 1) normally, we in distributions (SUSE for me) unshade the things anyway. 2) then javapackages-bootstrap in Fedora, as I saw call the new Modello() construtor. Also this change is in line with what was done in the tests when moving from plexus-containers to jsr330. After, I don't mind any other solution that works and that works also unshaded.
I don't care about the commit that adds the exception. But I would really love to have it working as it was before. Just adding cdi-api for something that can be done with existing dependencies...
Now, I am not the one who decides. I would still prefer this, since the tests use exactly the same.

**Comment by fridrich** [comment]
I am just wondering whether one cannot just simply apply that one commit and then maybe shade artifacts, which means that I can unshade it in the package without having to patch the logic that relied on shade plugin?

**Comment by cstamas** [comment]
Yes, will see about that. Am not at desk, so you can do it as well (pr against branchin this pr), will see tomorrow.

**Comment by fridrich** [comment]
Here are fedora tools that call the Modello constructor:
https://github.com/fedora-java/javapackages-bootstrap/blob/master/mbi/modello/src/org/fedoraproject/mbi/tool/modello/ModelloTool.java#L80

**Comment by fridrich** [comment]
Closing in favour of https://github.com/codehaus-plexus/modello/pull/452

**Pull request closed without merging**
