### PR TITLE
Fix Snakeyaml

### PR DESCRIPTION
**Pull request by cstamas**
Move to 2.2, but cannot get past one error: seems Model is not imported in writer (in reader is)??

Help!

### CODE REVIEW

**Comment by fridrich** [comment]
[0001-Fix-fix-SnakeYaml.patch.gz](https://github.com/codehaus-plexus/modello/files/15201807/0001-Fix-fix-SnakeYaml.patch.gz)
OK, I had a look and this is my finding: I took some of your changes from https://github.com/codehaus-plexus/modello/pull/419/commits/a8b7aacc5f747aed6d931dcb89048538327cb5d2 and I changed the model. It looks like you cannot make snakeyaml-writer and snakeyaml-extended-reader from the same model. Because the extended reader requires  locationTracker parameter in the root element. But with this parameter, the AbstractJavaModelloGenerator::isTrackingSupport is true and the class Model will be not relevant (isRelevant == false) and it will not be returned by getClasses(objectModel) in SnakeYamlWriterGenerator.
With the changes it produces compilable code.

**Comment by fridrich** [comment]
Also I changed the org.apache.maven.model package to org.codehaus.modello.test.model, because maven has itself the org.apache.maven.model.Model class in the org.apache.maven:maven-model artifact and it is safer to not have two unrelated classes on the classpath with the same full qualified name.

**Comment by cstamas** [comment]
Applied and yay! Thanks @fridrich a lot!

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
I hope it is fix for: #367 and suppresses #419

**Pull request merged**
